# UCL AI Society Machine Learning Tutorials
### Session 01. Introduction to Numpy, Pandas and Matplotlib Libraries

### Contents
1. Numpy
2. Pandas
3. Matplotlib

### Aim
At the end of this session, you will be able to:
- Understand the basics of numpy.
- Understand the basics of pandas.
- Understand the basics of matplotlib.
- Build a simple EDA (Exploratory Data Analysis) using above libraries.

## 1. Numpy
In recent years, Python have been highlighted as a programming language in the field of data science because it is easy to learn and supported by a number of scientific computing libraries. Numpy is one of the vital library that deals with data and enables users to compute multi-dimensional array data structure more efficiently and easier.

### 1.1 Basics of Numpy

In [ ]:
# Run this shell if you didn't install numpy
!pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

In [ ]:
a = np.array([1, 2, 3, 4]) # create a rank 1 array
print("Type of a: ", type(a))
print("Shape of a: ", a.shape)
print("The first element of a: ", a[0])
print("The last element of a: ", a[-1])

In [ ]:
# create an array full of ones
b = np.ones((2, 2))
print("Matrix b")
print(b)

# create an array full of zeros
c = np.zeros((2, 3))
print("\nMatrix c")
print(b)

# create an identity matrix
d = np.eye(3)
print("\nMatrix d")
print(d)

# create an array filled with random numbers between 0 and 1
e = np.random.random((2, 2))
print("\nMatrix e")
print(e)

### 1.2 Matrix of Numpy

- `np.transpose()` : Transpose of an array
- `np.dot(a, b)` : Dot product of two arrays
- `np.linalg.inv()` : Inverse matrix of an array (only valid to square matrix, having the dimension of n * n)
- `np.diagonal()` : Diagonal components of an array
- `a.reshape(row = x, column = y)` : Reshape an array

In [ ]:
x = np.array([
    [3, 11, 1],
    [7, 5, 2],
    [6, 8, 9],
    [0, 10, 4]
])

In [ ]:
# To Do: Transpose an array
# Expected outcome:
# [[ 3  7  6  0]
#  [11  5  8 10]
#  [ 1  2  9  4]]
transpose_x = None
print(transpose_x)

In [ ]:
# To Do: Dot product of two arrays: original x and transposed x
# Expected outcome:
# [[131  78 115 114]
#  [ 78  78 100  58]
#  [115 100 181 116]
#  [114  58 116 116]]
y = None
print(y)

In [ ]:
# To Do: Extract the diagonal elements of an array
# Expected outcome: [3 5 9]
diag_x = None
print(diag_x)

In [ ]:
# To Do: Reshape an array to columns of 2 and rows of 6
# Expected outcome:
# [[ 3 11]
#  [ 1  7]
#  [ 5  2]
#  [ 6  8]
#  [ 9  0]
#  [10  4]]
reshape_x = None
print(reshape_x)

### 1.3 Statistics of Numpy

- `np.sum()` : Array-wise sum
- `np.max()` : Array-wise maximum value
- `np.min(axis = 0)` : Minimum value of an array row
- `np.mean()` : Mean
- `np.median()` : Median
- `np.std()` : Standard deviation
- `np.corrcoef()` : Correlation coefficient [Correlation coefficient on Wikipedia](https://en.wikipedia.org/wiki/Correlation_coefficient)

In [ ]:
x = np.array(
    [34, 56, 6, 3, 9, 89, 120, 12, 201],
    dtype = np.int32
)

In [ ]:
# To Do: Summation of elements 
# Expected outcome: 530
sum = None
print(sum)

In [ ]:
# To Do: Minimum element in the array
# Expected outcome: 3
min = None
print(min)

In [ ]:
# To Do: Maximum element in the array
# Expected outcome: 201
max = None
print(max)

In [ ]:
# To Do: Average value of elements in the array
# Expected outcome: 58.89
mean = None
print(mean)

In [ ]:
# To Do: Median element in the array
# Expected outcome: 34.0
median = None
print(median)

In [ ]:
# To Do: Standard deviation of the array
# Expected outcome: 63.3095471902311
std = None
print(std)

### 1.4 Exersies

In [ ]:
x = np.array([
    [1, 52, 22, 2, 31, 65, 7, 8, 24, 10],
    [12, 2322, 33, 1, 2, 3, 99, 24, 1, 42],
    [623, 24, 3, 56, 5, 2, 7, 85, 22, 110],
    [63, 4, 3, 4, 5, 64, 7, 82, 3, 20],
    [48, 8, 3, 24, 57, 63, 7, 8, 9, 1032],
    [33, 64, 0, 24, 5, 6, 72, 832, 3, 10],
    [12, 242, 2, 11, 52, 63, 32, 8, 96, 2],
    [13, 223, 52, 4, 35, 62, 7, 8, 9, 10],
    [19, 2, 3, 149, 15, 6, 172, 2, 2, 11],
    [34, 23, 32, 24, 54, 63, 1, 5, 92, 7]
])

In [ ]:
x.shape

In [ ]:
# To Do: Extract the first column of x
# expected outcome: [1 12 623 63 48 33 12 13 19 34]
firstcol_x = None
print(firstcol_x)

In [ ]:
# To Do: extract the last row of x
# expected outcome: [34 23 32 24 54 63 1 5 92 7]
lastrow_x = None
print(lastrow_x)

In [ ]:
# To Do: calculate the mean of elements in the last row
# expected outcome: 33.5
mean_lastrow = None
print(mean_lastrow)

In [ ]:
# To Do : calculate the diagonal components of x
# expected outcome: [1 2322 3 4 57 6 32 8 2 7]
diag_x = None
print(diag_x)

In [ ]:
# To Do: calculate the variatoin of the Diagonal components of x
# expected outcome: 479979.9600000001
var_diag = None
print(var_diag)

### 1.5 (Advanced)  Numpy Problem

In [ ]:
def solution():
    prime = [2, 3, 5, 7, 11]

    matrix = [
        # TODO: Try making your own matrix by using the list 'prime'
        # TODO: Try doing sth awesome. Don't just write tons of numbers
        None
              ]
    # TODO: make it a numpy array
    matrix = None
    # TODO: What is Diagonal of the above matrix?
    matrix_dia = None

    # TODO: What are the sum and mean of the diagonal components?
    dia_sum = None
    dia_mean = None

    return matrix, dia_sum, dia_mean

In [ ]:
# Function for printing your answers
def print_answer(**kwargs):
    for key in kwargs.keys():
        print(key, ":", kwargs[key])

In [ ]:
matrix, dia_sum, dia_mean = solution()

In [ ]:
print_answer(matrix=matrix, dia_sum=dia_sum, dia_mean=dia_mean)

### What to do next?
Below websites would be helpful for your further study on numpy library:
- [A Visual Intro to NumPy and Data Representation](https://jalammar.github.io/visual-numpy/?fbclid=IwAR2MT-imY4dKpUcfHWfjdPOROUBadObVO7Wftf1detHWZCxSwNeA5paVI08)
- [Stanford CS231n Python Numpy Tutorial](http://cs231n.github.io/python-numpy-tutorial/)
- [DataCamp Python Numpy Array Tutorial](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)
- [Machine Learning Plus 101 Numpy Exercises for Data Analysis (Python)](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)